image: ${DEVOPS_REGISTRY}usgs/centos:latest

stages:
  - test
  - integration
  - deploy

variables:
  CI_REGISTRY: ${CODE_REGISTRY}
  CI_REGISTRY_IMAGE: ${CODE_REGISTRY_IMAGE}

## --------------------------------------------------
# Templates
## --------------------------------------------------

.check_code:
  cache: {}
  image: usgs/centos:latest
  script:
    - yum install -y wget which
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update --yes conda
    - conda info -a
    # Install Project Dependencies
    - conda config --add channels conda-forge
    - conda install python=${PYTHON_VERSION} obspy pycurl
    - pip install pipenv
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - pipenv --site-packages install --dev --pre --skip-lock
    # Run Code Checks
    - pipenv run black --check .
    - pipenv run pytest --cov-report xml:cov.xml --cov=test/
  artifacts:
    paths:
      - cov.xml
    reports:
      junit: cov.xml
  stage: test
  tags:
    - development
  variables:
    PYTHON_VERSION: 3.8

## --------------------------------------------------
# Test Stage
## --------------------------------------------------

Check Python 3.6:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.6'

Check Python 3.7:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.7'

Check Python 3.8:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.8'
