image: ${DEVOPS_REGISTRY}usgs/centos:latest

stages:
  - test
  - integration
  - deploy

variables:
  CI_REGISTRY: ${CODE_REGISTRY}
  CI_REGISTRY_IMAGE: ${CODE_REGISTRY_IMAGE}

## --------------------------------------------------
# Templates
## --------------------------------------------------

.check_code:
  cache: {}
  image: ${DEVOPS_REGISTRY}usgs/conda:latest
  script:
    # Add conda to path
    - source /etc/profile.d/conda.sh
    # Install Project Dependencies
    - conda config --add channels conda-forge
    - conda install python=${PYTHON_VERSION} obspy pycurl
    - pip install pipenv
    - pipenv --site-packages install --dev --pre --skip-lock
    # Run Code Checks
    - pipenv run black --check .
    - pipenv run pytest --cov-report xml:cov.xml --cov=geomagio
  artifacts:
    paths:
      - cov.xml
    reports:
      junit: cov.xml
  stage: test
  tags:
    - development
  variables:
    PYTHON_VERSION: 3.8

## --------------------------------------------------
# Test Stage
## --------------------------------------------------

Check Python 3.6:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.6'

Check Python 3.7:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.7'

Check Python 3.8:
  extends:
    - .check_code
  variables:
    PYTHON_VERSION: '3.8'
